In [1]:
import pandas as pd
from sklearn.ensemble import RandomForestClassifier
from sklearn.datasets import make_classification
from sklearn.model_selection import train_test_split
from sklearn import metrics

In [2]:
df1 = pd.read_csv('spam.csv',encoding = "ISO-8859-1")

In [3]:
sd=df1.drop(['Unnamed: 2','Unnamed: 3','Unnamed: 4'],axis=1)
sd

v1                                                 v2
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...
...    ...                                                ...
5567  spam  This is the 2nd time we have tried 2 contact u...
5568   ham              Will Ì_ b going to esplanade fr home?
5569   ham  Pity, * was in mood for that. So...any other s...
5570   ham  The guy did some bitching but I acted like i'd...
5571   ham                         Rofl. Its true to its name

[5572 rows x 2 columns]

In [4]:
df3 = sd.rename(columns = {'v1': 'Spam/ham', 'v2': 'text'}, inplace = False)
df3

Spam/ham                                               text
0         ham  Go until jurong point, crazy.. Available only ...
1         ham                      Ok lar... Joking wif u oni...
2        spam  Free entry in 2 a wkly comp to win FA Cup fina...
3         ham  U dun say so early hor... U c already then say...
4         ham  Nah I don't think he goes to usf, he lives aro...
...       ...                                                ...
5567     spam  This is the 2nd time we have tried 2 contact u...
5568      ham              Will Ì_ b going to esplanade fr home?
5569      ham  Pity, * was in mood for that. So...any other s...
5570      ham  The guy did some bitching but I acted like i'd...
5571      ham                         Rofl. Its true to its name

[5572 rows x 2 columns]

In [5]:
df3['spam']=0

In [6]:
df3.loc[df3['Spam/ham'] == 'spam', 'spam'] = 1

In [7]:
df3

Spam/ham                                               text  spam
0         ham  Go until jurong point, crazy.. Available only ...     0
1         ham                      Ok lar... Joking wif u oni...     0
2        spam  Free entry in 2 a wkly comp to win FA Cup fina...     1
3         ham  U dun say so early hor... U c already then say...     0
4         ham  Nah I don't think he goes to usf, he lives aro...     0
...       ...                                                ...   ...
5567     spam  This is the 2nd time we have tried 2 contact u...     1
5568      ham              Will Ì_ b going to esplanade fr home?     0
5569      ham  Pity, * was in mood for that. So...any other s...     0
5570      ham  The guy did some bitching but I acted like i'd...     0
5571      ham                         Rofl. Its true to its name     0

[5572 rows x 3 columns]

In [8]:
df=df3.drop(['Spam/ham'],axis=1)
df

text  spam
0     Go until jurong point, crazy.. Available only ...     0
1                         Ok lar... Joking wif u oni...     0
2     Free entry in 2 a wkly comp to win FA Cup fina...     1
3     U dun say so early hor... U c already then say...     0
4     Nah I don't think he goes to usf, he lives aro...     0
...                                                 ...   ...
5567  This is the 2nd time we have tried 2 contact u...     1
5568              Will Ì_ b going to esplanade fr home?     0
5569  Pity, * was in mood for that. So...any other s...     0
5570  The guy did some bitching but I acted like i'd...     0
5571                         Rofl. Its true to its name     0

[5572 rows x 2 columns]

In [9]:
with pd.option_context('display.max_rows', 5728):
    print (df)

                                                   text  spam
0     Go until jurong point, crazy.. Available only ...     0
1                         Ok lar... Joking wif u oni...     0
2     Free entry in 2 a wkly comp to win FA Cup fina...     1
3     U dun say so early hor... U c already then say...     0
4     Nah I don't think he goes to usf, he lives aro...     0
5     FreeMsg Hey there darling it's been 3 week's n...     1
6     Even my brother is not like to speak with me. ...     0
7     As per your request 'Melle Melle (Oru Minnamin...     0
8     WINNER!! As a valued network customer you have...     1
9     Had your mobile 11 months or more? U R entitle...     1
10    I'm gonna be home soon and i don't want to tal...     0
11    SIX chances to win CASH! From 100 to 20,000 po...     1
12    URGENT! You have won a 1 week FREE membership ...     1
13    I've been searching for the right words to tha...     0
14                  I HAVE A DATE ON SUNDAY WITH WILL!!     0
15    XX

In [10]:
X, y = make_classification(n_samples=2736, n_features=2, n_informative=2, n_redundant=0, random_state=5)

In [11]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3)

In [12]:
classify = RandomForestClassifier(n_estimators=20, random_state=5)
classify

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
                       max_depth=None, max_features='auto', max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=20,
                       n_jobs=None, oob_score=False, random_state=5, verbose=0,
                       warm_start=False)

In [13]:
classify.fit(X, y)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
                       max_depth=None, max_features='auto', max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=20,
                       n_jobs=None, oob_score=False, random_state=5, verbose=0,
                       warm_start=False)

In [14]:
y_pred = classify.predict(X_test)

In [15]:
classify.apply(X)

array([[ 32,  77,  42, ...,  20,  22,  28],
       [125, 152, 136, ..., 196, 178,  88],
       [251, 256, 256, ..., 251, 239, 231],
       ...,
       [ 30,  28,  29, ...,  20,  12,  45],
       [233, 243, 246, ..., 239, 231, 211],
       [ 32,  77,  42, ...,  20,  22,  28]], dtype=int64)

In [16]:
classify.decision_path(X)

(<2736x5196 sparse matrix of type '<class 'numpy.int64'>'
 	with 482453 stored elements in Compressed Sparse Row format>,
 array([   0,  271,  544,  819, 1118, 1375, 1638, 1891, 2152, 2437, 2698,
        2967, 3204, 3447, 3678, 3947, 4168, 4427, 4706, 4953, 5196],
       dtype=int32))

In [17]:
classify.get_params(deep=True)

{'bootstrap': True,
 'class_weight': None,
 'criterion': 'gini',
 'max_depth': None,
 'max_features': 'auto',
 'max_leaf_nodes': None,
 'min_impurity_decrease': 0.0,
 'min_impurity_split': None,
 'min_samples_leaf': 1,
 'min_samples_split': 2,
 'min_weight_fraction_leaf': 0.0,
 'n_estimators': 20,
 'n_jobs': None,
 'oob_score': False,
 'random_state': 5,
 'verbose': 0,
 'warm_start': False}

In [18]:
classify.predict_log_proba(X)

C:\Users\Me\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:635: RuntimeWarning: divide by zero encountered in log
  return np.log(proba)


array([[  0., -inf],
       [-inf,   0.],
       [-inf,   0.],
       ...,
       [  0., -inf],
       [-inf,   0.],
       [  0., -inf]])

In [19]:
classify.predict_proba(X)

array([[1., 0.],
       [0., 1.],
       [0., 1.],
       ...,
       [1., 0.],
       [0., 1.],
       [1., 0.]])

In [20]:
classify.score(X, y)

0.9974415204678363